### PR TITLE
remove task name

### PR DESCRIPTION
**Pull request by tsel-59**

### CODE REVIEW

**Comment by tsel-59** [comment]
I can't run the tests locally, so this will have test failures

**Comment by marickvantuil** [comment]
A pre-defined task name was heavily used and expected in some places in the package. Removing it caused too much things to break, sadly! Apologies, my suggestion was too vigorous 😛. Therefore, as a compromise, I've changed it to using a hashed value for the task ID. What do you think?

**Comment by tsel-59** [comment]
it would be helpful to make the suffix the $displayName so that we can still search by job in the the GCP dashboard. Seems like google just wants the prefix of the job to be a randomized hash.

**Comment by marickvantuil** [comment]
Hey, I'm going to close this PR - v4 of the package will prefix the task name with a random hash

**Pull request closed without merging**
