### PR TITLE
Upgrade JWT Package

### PR DESCRIPTION
**Pull request by gogl92**
This old version needs to be upgraded to avoid problems with other dependencies like Laravel Passport.

### CODE REVIEW

**Comment by marickvantuil** [comment]
It's currently not yet possible to update JWT to 6.x because `google/auth` (that this package uses to verify OpenID tokens) doesn't yet support JWT 6.x. It was fixed [3 weeks ago](https://github.com/googleapis/google-auth-library-php/issues/399), but no version is tagged yet. What problems is this causing?

**Comment by gogl92** [comment]
I want to use Laravel 9 in my project but I use Laravel Passport which also uses the JWT package so I'm unable to use both packages due to the difference in versions.

**Comment by bshaffer** [comment]
BTW this has now been fixed and tagged in [v1.21.1](https://github.com/googleapis/google-auth-library-php/releases/tag/v1.21.1)

**Comment by marickvantuil** [comment]
Released v3.1.3 with this fix, thanks @gogl92 and @bshaffer!

**Pull request merged**
